sudo: true

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopenblas-dev
      - liblapacke-dev

matrix:
  include:
    #########
    # Linux Machines
    #########
    - os: linux

    #########
    # OSx Machines
    #########
    - os: osx


before_install:
  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"

  # Travis machines have 2 cores
  - JOBS=2

  - cd "${DEPS_DIR}"

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - CMAKE_VERSION=3.10.1
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake
      brew install openblas
    fi
  - which cmake
  - cmake --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - export CMAKE_OPTIONS="-DCMAKE_CXX_STANDARD=11 -DBLA_VENDOR=OpenBLAS"
  # - |
  #   if [[ "${BUILD_STATIC}" == "ON" ]]; then
  #     export CMAKE_OPTIONS="${CMAKE_OPTIONS} -DBLA_STATIC=ON"
  #   fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo $LD_LIBRARY_PATH; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then echo $DYLD_LIBRARY_PATH; fi
  - echo "cmake .. ${CMAKE_OPTIONS}"
  - cmake .. ${CMAKE_OPTIONS}
  - make VERBOSE=1
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      ldd ./CMakeHelloWorld
    else  # Mac
      otool -L ./CMakeHelloWorld
    fi

after_success:
  - ./CMakeHelloWorld

notifications:
  email: false
