sudo: true

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopenblas-dev
      - liblapacke-dev

matrix:
  include:
    #########
    # Linux Machines
    #########
    - os: linux

    #########
    # OSx Machines
    #########
    - os: osx


before_install:
  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"

  # Travis machines have 2 cores
  - JOBS=2

  - cd "${DEPS_DIR}"

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - CMAKE_VERSION=3.10.1
  - curl -fsSkL https://raw.githubusercontent.com/openmeeg/ci-utils/master/travis/install_cmake.sh > x.sh && source ./x.sh

  ############################################################################
  # Install OpenBLAS
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      rm -rf /usr/local/include/c++
      brew install openblas
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - export CMAKE_OPTIONS="-DCMAKE_CXX_STANDARD=11 -DBLA_VENDOR=OpenBLAS"
  # - |
  #   if [[ "${BUILD_STATIC}" == "ON" ]]; then
  #     export CMAKE_OPTIONS="${CMAKE_OPTIONS} -DBLA_STATIC=ON"
  #   fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo $LD_LIBRARY_PATH; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then echo $DYLD_LIBRARY_PATH; fi
  - echo "cmake .. ${CMAKE_OPTIONS}"
  - cmake .. ${CMAKE_OPTIONS}
  - make VERBOSE=1
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      ldd ./CMakeHelloWorld
    else  # Mac
      otool -L ./CMakeHelloWorld
    fi

after_success:
  - ./CMakeHelloWorld

notifications:
  email: false
